### PR TITLE
Fix link syntax in footer

### PR DESCRIPTION
**Pull request by Spone**

### CODE REVIEW

**Review by adipasquale — APPROVED** [review]
Welcome @Spone ! thank you for your contribution 🙇 

Are you using this gem in one of your project?

(we tend to speak in english in this github repo with @freesteph but if you'd rather we spoke french let us know!)

**Comment by Spone** [comment]
Hi @adipasquale! I'm just following open source projects using ViewComponent out of curiosity and I noticed this bug in the footer :)

**Comment by adipasquale** [comment]
great ! thanks.

I missed an error in your PR though

in HAML attributes can either use a ruby-like syntax with curly brackets `a{href: "url.com"}` or a html-like syntax with square brackets `div[href="url.com"]`. You seem to have mixed both :)

cf https://haml.info/docs/yardoc/file.REFERENCE.html#attributes

**Comment by Spone** [comment]
> You seem to have mixed both :)

Ha! You're right. I'm more used to writing Slim than Haml ;)
It's fixed.

**Comment by freesteph** [comment]
Thanks @Spone !

**Pull request merged**
